GET http://localhost:3000/event?id=3

###

POST http://localhost:3000/event
Content-Type: application/json

{
    "title": "X-MAS"
}

###

DELETE http://localhost:3000/event?id=2

###

PATCH http://localhost:3000/event?id=1
Content-Type: application/json

{
    "title": "B-day"
}